louisepaul75/nextjs15-social-media-app-clone

src/app/(auth)/actions.ts
sign up action session validation function error fixed
=> sign up action session validation function error fixed

src/app/(auth)/signup/SignUpForm.tsx, src/app/(auth)/signup/page.tsx
=> signup form layout moified

src/app/(auth)/login/page.tsx
login page theme color modified
=> login page theme color modified

src/app/(auth)/login/LoginForm.tsx
=> login form package updated

src/app/(auth)/login/LoginForm.tsx
loginform state variable changed
=> loginform state variable changed

src/app/(auth)/login/actions.ts
validatePassword function added to login action
=> validatePassword function added to login action

src/app/(auth)/login/google/route.ts
cookies set funtion added to login google
=> cookies set funtion added to login google

src/app/(auth)/login/google/GoogleSignInButton.tsx
=> google auth page added

src/app/(main)/page.tsx
=> main page css modified

src/app/(main)/NotificationsButton.tsx
notification interface modified
=> notification interface modified

src/app/(main)/not-found.tsx
=> 404 page added

src/app/(main)/MessagesButton.tsx
messagbutton interface and style modified
=> messagbutton interface and style modified

src/app/(main)/MenuBar.tsx
=> menubar style modified

src/app/(main)/loading.tsx
=> loading page added

src/app/(main)/layout.tsx
=> main layout modified

src/lib/ky.ts, src/lib/prisma.ts
lib/ key and prisma function modified
=> lib/ key and prisma function modified

src/lib/stream.ts
=> streamchat config modified

src/lib/types.ts
=> prisma types modified

src/lib/uploadthing.ts
=> upload helper modified

src/lib/utils.ts
=> formateDate util modified

src/hooks/useDebounce.ts, src/hooks/useFollowerInfo.ts
=> hook modified

src/components/UserTooltip.tsx
userToolTip interface modified
=> userToolTip interface modified

src/components/UserLinkWithTooltip.tsx
userLinkWithToolTip interface modified
=> userLinkWithToolTip interface modified

src/components/UserButton.tsx
=> userButton interface modified

src/components/UserAvatar.tsx
=> userAvater interface added

src/components/TrendsSidebar.tsx
trendsidbar interface modified
=> trendsidbar interface modified

src/components/SearchField.tsx
=> searchfiled style modified

src/components/PasswordInput.tsx
=> passwordinput style modified

src/components/Linkify.tsx
linkify interface and style modified
=> linkify interface and style modified
